words = [
  { word: "mie", synonyms: ["peri", "kapi", "wash"] }, // A
  { word: "banja", synonyms: ["tusira", "mie", "pliva"] }, // B
  { word: "wash", synonyms: ["clean", "banja", "peri"] },
  { word: "elena", synonyms: ["andrej", "angela", "damjan"] },
  /*   {
    word: "happy",
    synonyms: [
      "cheerful",
      "delighted",
      "ecstatic",
      "exultant",
      "glad",
      "gleeful",
      "jolly",
      "joyful",
      "joyous",
      "jubilant",
      "merry",
      "overjoyed",
    ],
  },
  {
    word: "glad",
    synonyms: [
      "happy",
      "delighted",
      "pleased",
      "elated",
      "joyful",
      "joyous",
      ,
      "gleeful",
      "cheerful",
      "exhilarated",
      "contented",
    ],
  },
  {
    word: "joyous",
    synonyms: [
      "happy",
      "glad",
      "gladsome",
      "joyful",
      "festive",
      "wonderful",
      "rapturous",
      "mirthful",
      "merry",
      "cheerful",
      "gleeful",
    ],
  },
  {
    word: "wash",
    synonyms: [
      "clean",
      "cleanse",
      "sponge",
      "scrub",
      "wipe",
      "scour",
      "lave",
      "mop",
      "hose down",
      "squeegee",
      "sluice (down)",
      "swill (down)",
      "douse",
      "swab (down)",
      "flush",
      "disinfect",
      "launder",
      "rinse (out)",
      "dry-clean",
      "shampoo",
    ],
  },
  {
    word: "clean",
    synonyms: [
      "wash",
      "cleanse",
      "wipe",
      "sponge",
      "scrub",
      "mop",
      "rinse",
      "scour",
      "swab",
      "flush",
      "polish",
      "disinfect",
      "shampoo",
      "floss",
      "lave",
      "launder",
      "      dry-clean",
    ],
  },
  {
    word: "wipe",
    synonyms: [
      "rub",
      "clean",
      "mop",
      "sponge",
      "swab",
      "      dry",
      "      polish",
    ],
  }, */
];
module.exports = { words };
