const words = [
  {
    word: "happy",
    synonyms: [
      "cheerful",
      "delighted",
      "ecstatic",
      "exultant",
      "glad",
      "gleeful",
      "jolly",
      "joyful",
      "joyous",
      "jubilant",
      "merry",
      "overjoyed",
    ],
  },
  {
    word: "glad",
    synonyms: [
      "happy",
      "delighted",
      "pleased",
      "elated",
      "joyful",
      "joyous",
      ,
      "gleeful",
      "cheerful",
      "exhilarated",
      "contented",
    ],
  },
  {
    word: "joyous",
    synonyms: [
      "happy",
      "glad",
      "gladsome",
      "joyful",
      "festive",
      "wonderful",
      "rapturous",
      "mirthful",
      "merry",
      "cheerful",
      "gleeful",
    ],
  },
  {
    word: "wash",
    synonyms: [
      "clean",
      "cleanse",
      "sponge",
      "scrub",
      "wipe",
      "scour",
      "lave",
      "mop",
      "hose down",
      "squeegee",
      "sluice (down)",
      "swill (down)",
      "douse",
      "swab (down)",
      "flush",
      "disinfect",
      "launder",
      "rinse (out)",
      "dry-clean",
      "shampoo",
    ],
  },
  {
    word: "clean",
    synonyms: [
      "wash",
      "cleanse",
      "wipe",
      "sponge",
      "scrub",
      "mop",
      "rinse",
      "scour",
      "swab",
      "flush",
      "polish",
      "disinfect",
      "shampoo",
      "floss",
      "lave",
      "launder",
      "dry-clean",
    ],
  },
  {
    word: "wipe",
    synonyms: [
      "rub",
      "clean",
      "mop",
      "sponge",
      "swab",
      "      dry",
      "      polish",
    ],
  },
  {
    word: "boisterous",
    synonyms: [
      "rambunctious",
      "robustious",
      "rumbustious",
      "unruly|knockabout|fierce",
      "rough",
    ],
  },
  {
    word: "monastic",
    synonyms: ["cloistered", "cloistral", "conventual", "monastical"],
  },
  {
    word: "dull",
    synonyms: [
      "muffle",
      "mute",
      "damp",
      "dampen",
      "tone down|numb",
      "benumb",
      "blunt|blunt|pall",
    ],
  },
  {
    word: "tympanuchus pallidicinctus",
    synonyms: ["lesser prairie chicken", "Tympanuchus pallidicinctus"],
  },
  {
    word: "agrippa",
    synonyms: ["Agrippa", "Marcus Vipsanius Agrippa"],
  },
  {
    word: "eastern orthodox",
    synonyms: [
      "Orthodox",
      "Eastern Orthodox",
      "Russian Orthodox",
      "Greek Orthodox",
    ],
  },
  { word: "fodder", synonyms: ["cannon fodder", "fresh fish"] },
  { word: "epiphyllum", synonyms: ["orchid cactus"] },
  { word: "in conclusion", synonyms: ["last", "lastly", "finally"] },
  {
    word: "ferdinand victor eugene delacroix",
    synonyms: [
      "Delacroix",
      "Eugene Delacroix",
      "Ferdinand Victor Eugene Delacroix",
    ],
  },
  { word: "diclofenac sodium", synonyms: ["Voltaren"] },
  { word: "satisfied", synonyms: ["quenched", "slaked"] },
  { word: "scrubby", synonyms: ["scrabbly|scrawny", "stunted"] },
  {
    word: "erb-duchenne paralysis",
    synonyms: ["Erb's palsy", "Erb-Duchenne paralysis"],
  },
  {
    word: "dipterous insect",
    synonyms: ["two-winged insects", "dipteran", "dipteron"],
  },
  {
    word: "fibrovascular bundle",
    synonyms: ["vascular bundle", "vascular strand"],
  },
  {
    word: "eranthis hyemalis",
    synonyms: ["winter aconite", "Eranthis hyemalis"],
  },
  { word: "displacement reaction", synonyms: ["displacement"] },
  { word: "elizabeth ii", synonyms: ["Elizabeth", "Elizabeth II"] },
  { word: "irreconcilable", synonyms: ["unreconcilable"] },
  {
    word: "edward roscoe murrow",
    synonyms: ["Murrow", "Edward R. Murrow", "Edward Roscoe Murrow"],
  },
  {
    word: "east germany",
    synonyms: ["East Germany", "German Democratic Republic"],
  },
  {
    word: "eryngium maritimum",
    synonyms: ["sea holly", "sea holm", "sea eryngium", "Eryngium maritimum"],
  },
  {
    word: "ac",
    synonyms: [
      "actinium",
      "Ac",
      "atomic number 89|alternating current",
      "AC",
      "alternating electric current",
    ],
  },
  { word: "lineal", synonyms: ["direct"] },
  {
    word: "dutchman's breeches",
    synonyms: ["Dutchman's breeches", "Dicentra cucullaria"],
  },
  {
    word: "elongated",
    synonyms: ["extended", "lengthened", "prolonged|elongate"],
  },
  { word: "thinly", synonyms: ["thin|lightly"] },
  {
    word: "full",
    synonyms: ["entire", "total|total|replete|good|broad|wide", "wide-cut"],
  },
  { word: "single-celled", synonyms: ["one-celled"] },
  {
    word: "lamented",
    synonyms: ["lament", "keen|deplore", "lament", "bewail", "bemoan"],
  },
  { word: "rust", synonyms: ["rusty", "rust-brown"] },
  { word: "female horse", synonyms: ["mare"] },
  { word: "dwarf buckeye", synonyms: ["bottlebrush buckeye"] },
  {
    word: "foiled",
    synonyms: [
      "foil|thwart",
      "queer",
      "spoil",
      "scotch",
      "foil",
      "cross",
      "frustrate",
      "baffle",
      "bilk|foil",
    ],
  },
  {
    word: "salientian",
    synonyms: ["frog", "toad", "toad frog", "anuran", "batrachian"],
  },
  { word: "dink", synonyms: ["DINK|drop shot"] },
  {
    word: "fantasy",
    synonyms: ["phantasy|phantasy|illusion", "phantasy", "fancy"],
  },
  {
    word: "dichloroethyl sulfide",
    synonyms: [
      "mustard gas",
      "mustard agent",
      "blistering agent",
      "sulfur mustard",
    ],
  },
  {
    word: "euphorbia medusae",
    synonyms: ["medusa's head", "Euphorbia medusae", "Euphorbia caput-medusae"],
  },
  {
    word: "epsilon toxin",
    synonyms: ["Clostridium perfringens epsilon toxin"],
  },
  {
    word: "expectant",
    synonyms: [
      "anticipant",
      "anticipative|big",
      "enceinte",
      "gravid",
      "great",
      "large",
      "heavy",
      "with child",
    ],
  },
  { word: "seasick", synonyms: ["airsick", "air sick", "carsick"] },
  {
    word: "drooping",
    synonyms: [
      "flagging|droopy",
      "sagging|cernuous",
      "nodding",
      "pendulous",
      "weeping",
    ],
  },
  {
    word: "dutch iris",
    synonyms: ["Dutch iris", "Iris tingitana|Dutch iris", "Iris filifolia"],
  },
  {
    word: "lessened",
    synonyms: ["diminished", "vitiated", "weakened"],
  },
  {
    word: "fatty",
    synonyms: ["fatso", "fat person", "roly-poly", "butterball"],
  },
  {
    word: "farmhand",
    synonyms: ["fieldhand", "field hand", "farm worker"],
  },
  { word: "saccharine", synonyms: ["cloying", "syrupy", "treacly"] },
  {
    word: "american bog asphodel",
    synonyms: ["American bog asphodel", "Narthecium americanum"],
  },
  { word: "throughout", synonyms: ["end-to-end|passim"] },
  {
    word: "eagerness",
    synonyms: [
      "avidity",
      "avidness",
      "keenness|readiness",
      "zeal",
      "forwardness",
    ],
  },
  { word: "labor-intensive", synonyms: ["labour-intensive"] },
  {
    word: "ameiurus melas",
    synonyms: ["horned pout", "hornpout", "pout", "Ameiurus Melas"],
  },
  { word: "repetitive", synonyms: ["repetitious"] },
  {
    word: "esteem",
    synonyms: [
      "respect",
      "value",
      "prize",
      "prise|think of",
      "repute",
      "regard as",
      "look upon",
      "look on",
      "take to be",
    ],
  },
  {
    word: "plumping",
    synonyms: [
      "plummet",
      "plump|plank",
      "flump",
      "plonk",
      "plop",
      "plunk",
      "plump down",
      "plunk down",
      "plump|fatten",
      "fat",
      "flesh out",
      "fill out",
      "plump",
      "plump out",
      "fatten out",
      "fatten up|plump",
      "go",
    ],
  },
  {
    word: "unclouded",
    synonyms: ["clean", "clear", "light|cloudless"],
  },
  {
    word: "american federalist party",
    synonyms: [
      "Federalist Party",
      "American Federalist Party",
      "Federal Party",
    ],
  },
  { word: "cynomys", synonyms: ["Cynomys", "genus Cynomys"] },
  {
    word: "ko'd",
    synonyms: ["knocked out", "kayoed", "KO'd", "out", "stunned"],
  },
  {
    word: "dinesen",
    synonyms: [
      "Dinesen",
      "Isak Dinesen",
      "Blixen",
      "Karen Blixen",
      "Baroness Karen Blixen",
    ],
  },
  {
    word: "dun",
    synonyms: ["greyish brown", "grayish brown", "fawn"],
  },
  { word: "animal foot", synonyms: ["foot"] },
  {
    word: "fatuousness",
    synonyms: ["absurdity", "fatuity", "silliness"],
  },
  { word: "culbertson", synonyms: ["Culbertson", "Ely Culbertson"] },
  { word: "common carotid", synonyms: ["common carotid artery"] },
  {
    word: "nonflavored",
    synonyms: ["unflavored", "unflavoured", "nonflavoured"],
  },
  {
    word: "ecuadoran monetary unit",
    synonyms: ["Ecuadoran monetary unit"],
  },
  { word: "ruling", synonyms: ["opinion"] },
  {
    word: "family ardeidae",
    synonyms: ["Ardeidae", "family Ardeidae"],
  },
  { word: "irritative", synonyms: ["irritating"] },
  { word: "transsexual", synonyms: ["transexual|transexual"] },
  { word: "judicial", synonyms: ["discriminative"] },
  { word: "browser", synonyms: ["web browser"] },
  {
    word: "diodon holocanthus",
    synonyms: ["balloonfish", "Diodon holocanthus"],
  },
  {
    word: "aplysiidae",
    synonyms: [
      "Aplysiidae",
      "family Aplysiidae",
      "Tethyidae",
      "family Tethyidae",
    ],
  },
  {
    word: "exacum affine",
    synonyms: ["Persian violet", "Exacum affine"],
  },
  {
    word: "field of battle",
    synonyms: ["battlefield", "battleground", "field of honor", "field"],
  },
  { word: "champaign", synonyms: ["plain", "field|Champaign"] },
  {
    word: "freewheeling",
    synonyms: ["freewheel", "drift|freewheel"],
  },
  { word: "cryptogram", synonyms: ["cryptograph", "secret writing"] },
  { word: "shoeless", synonyms: ["barefoot", "barefooted"] },
  {
    word: "touching",
    synonyms: [
      "touch|touch|touch",
      "stir|refer",
      "pertain",
      "relate",
      "concern",
      "come to",
      "bear on",
      "touch",
      "touch on",
      "have-to doe with|touch",
      "adjoin",
      "meet",
      "contact|affect",
      "impact",
      "bear upon",
      "bear on",
      "touch on",
      "touch|touch|touch|reach",
      "extend to",
      "touch|equal",
      "touch",
      "rival",
      "match|touch",
      "disturb|allude",
      "touch",
      "advert|touch|partake",
      "touch|tint",
      "tinct",
      "tinge",
      "touch",
    ],
  },
  {
    word: "forward",
    synonyms: [
      "forwards",
      "frontward",
      "frontwards",
      "forrad",
      "forrard|forth",
      "onward|ahead|ahead",
      "onward",
      "onwards",
      "forwards",
      "forrader|fore",
    ],
  },
  {
    word: "american egret",
    synonyms: ["American egret", "great white heron", "Egretta albus"],
  },
  { word: "dysgenics", synonyms: ["cacogenics"] },
  { word: "cladding", synonyms: ["facing"] },
  {
    word: "ecosoc commission",
    synonyms: ["Economic and Social Council commission", "ECOSOC commission"],
  },
  {
    word: "footling",
    synonyms: [
      "fiddling",
      "lilliputian",
      "little",
      "niggling",
      "piddling",
      "piffling",
      "petty",
      "picayune",
      "trivial",
    ],
  },
  {
    word: "counterpart",
    synonyms: ["opposite number", "vis-a-vis|similitude", "twin"],
  },
  {
    word: "edith newbold jones wharton",
    synonyms: ["Wharton", "Edith Wharton", "Edith Newbold Jones Wharton"],
  },
  {
    word: "arrest",
    synonyms: [
      "apprehension",
      "catch",
      "collar",
      "pinch",
      "taking into custody|check",
      "halt",
      "hitch",
      "stay",
      "stop",
      "stoppage",
    ],
  },
  {
    word: "dolichotis",
    synonyms: ["Dolichotis", "genus Dolichotis"],
  },
  {
    word: "doctor of arts",
    synonyms: ["Doctor of Arts", "ArtsD|Doctor of Arts", "D.A."],
  },
  {
    word: "crystal",
    synonyms: [
      "crystallization|quartz glass",
      "quartz",
      "vitreous silica",
      "lechatelierite|watch crystal",
      "watch glass",
    ],
  },
  {
    word: "catalina island",
    synonyms: ["Santa Catalina", "Catalina Island"],
  },
  {
    word: "stippled",
    synonyms: ["stipple|stipple|stipple|stipple", "speckle"],
  },
  {
    word: "iridescent",
    synonyms: [
      "changeable",
      "chatoyant",
      "shot|nacreous",
      "opalescent",
      "opaline",
      "pearlescent",
    ],
  },
  {
    word: "family plantaginaceae",
    synonyms: ["Plantaginaceae", "family Plantaginaceae", "plantain family"],
  },
  {
    word: "pernicious anemia",
    synonyms: ["pernicious anaemia", "malignant anemia", "malignant anaemia"],
  },
  {
    word: "fated",
    synonyms: [
      "destine",
      "fate",
      "doom",
      "designate|fatten",
      "fat",
      "flesh out",
      "fill out",
      "plump",
      "plump out",
      "fatten out",
      "fatten up",
    ],
  },
  {
    word: "foliated",
    synonyms: ["foliate|foliate|foliate|foliate", "paginate", "page|foliate"],
  },
  { word: "formative", synonyms: ["shaping", "plastic"] },
  {
    word: "heartsick",
    synonyms: ["brokenhearted", "heartbroken|despondent"],
  },
  {
    word: "footling",
    synonyms: [
      "loiter",
      "lounge",
      "footle",
      "lollygag",
      "loaf",
      "lallygag",
      "hang around",
      "mess about",
      "tarry",
      "linger",
      "lurk",
      "mill about",
      "mill around|footle",
    ],
  },
  { word: "corner", synonyms: ["tree"] },
  {
    word: "meretricious",
    synonyms: [
      "brassy",
      "cheap",
      "flash",
      "flashy",
      "garish",
      "gaudy",
      "gimcrack",
      "loud",
      "tacky",
      "tatty",
      "tawdry",
      "trashy|gilded",
      "specious",
    ],
  },
  {
    word: "genus stizolobium",
    synonyms: ["genus Mucuna", "Stizolobium", "genus Stizolobium"],
  },
  {
    word: "crucian carp",
    synonyms: ["Carassius carassius", "Carassius vulgaris"],
  },
];
module.exports = { words };
